// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: appbase.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SortDirection_Enum int32

const (
	SortDirection_Asc  SortDirection_Enum = 0
	SortDirection_Desc SortDirection_Enum = 1
)

// Enum value maps for SortDirection_Enum.
var (
	SortDirection_Enum_name = map[int32]string{
		0: "Asc",
		1: "Desc",
	}
	SortDirection_Enum_value = map[string]int32{
		"Asc":  0,
		"Desc": 1,
	}
)

func (x SortDirection_Enum) Enum() *SortDirection_Enum {
	p := new(SortDirection_Enum)
	*p = x
	return p
}

func (x SortDirection_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortDirection_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_appbase_proto_enumTypes[0].Descriptor()
}

func (SortDirection_Enum) Type() protoreflect.EnumType {
	return &file_appbase_proto_enumTypes[0]
}

func (x SortDirection_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortDirection_Enum.Descriptor instead.
func (SortDirection_Enum) EnumDescriptor() ([]byte, []int) {
	return file_appbase_proto_rawDescGZIP(), []int{2, 0}
}

type SortColumn_Enum int32

const (
	SortColumn_None     SortColumn_Enum = 0
	SortColumn_Name     SortColumn_Enum = 1
	SortColumn_Duration SortColumn_Enum = 2
)

// Enum value maps for SortColumn_Enum.
var (
	SortColumn_Enum_name = map[int32]string{
		0: "None",
		1: "Name",
		2: "Duration",
	}
	SortColumn_Enum_value = map[string]int32{
		"None":     0,
		"Name":     1,
		"Duration": 2,
	}
)

func (x SortColumn_Enum) Enum() *SortColumn_Enum {
	p := new(SortColumn_Enum)
	*p = x
	return p
}

func (x SortColumn_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortColumn_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_appbase_proto_enumTypes[1].Descriptor()
}

func (SortColumn_Enum) Type() protoreflect.EnumType {
	return &file_appbase_proto_enumTypes[1]
}

func (x SortColumn_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortColumn_Enum.Descriptor instead.
func (SortColumn_Enum) EnumDescriptor() ([]byte, []int) {
	return file_appbase_proto_rawDescGZIP(), []int{3, 0}
}

type Sample struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sha256    string `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Format    string `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	SourceUri string `protobuf:"bytes,3,opt,name=source_uri,json=sourceUri,proto3" json:"source_uri,omitempty"`
	Uri       string `protobuf:"bytes,4,opt,name=uri,proto3" json:"uri,omitempty"`
	Duration  int64  `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`
	Added     bool   `protobuf:"varint,6,opt,name=added,proto3" json:"added,omitempty"`
}

func (x *Sample) Reset() {
	*x = Sample{}
	if protoimpl.UnsafeEnabled {
		mi := &file_appbase_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sample) ProtoMessage() {}

func (x *Sample) ProtoReflect() protoreflect.Message {
	mi := &file_appbase_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sample.ProtoReflect.Descriptor instead.
func (*Sample) Descriptor() ([]byte, []int) {
	return file_appbase_proto_rawDescGZIP(), []int{0}
}

func (x *Sample) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *Sample) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *Sample) GetSourceUri() string {
	if x != nil {
		return x.SourceUri
	}
	return ""
}

func (x *Sample) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Sample) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Sample) GetAdded() bool {
	if x != nil {
		return x.Added
	}
	return false
}

type Source struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uri        string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
}

func (x *Source) Reset() {
	*x = Source{}
	if protoimpl.UnsafeEnabled {
		mi := &file_appbase_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_appbase_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_appbase_proto_rawDescGZIP(), []int{1}
}

func (x *Source) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Source) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

type SortDirection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SortDirection) Reset() {
	*x = SortDirection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_appbase_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SortDirection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortDirection) ProtoMessage() {}

func (x *SortDirection) ProtoReflect() protoreflect.Message {
	mi := &file_appbase_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortDirection.ProtoReflect.Descriptor instead.
func (*SortDirection) Descriptor() ([]byte, []int) {
	return file_appbase_proto_rawDescGZIP(), []int{2}
}

type SortColumn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SortColumn) Reset() {
	*x = SortColumn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_appbase_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SortColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortColumn) ProtoMessage() {}

func (x *SortColumn) ProtoReflect() protoreflect.Message {
	mi := &file_appbase_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortColumn.ProtoReflect.Descriptor instead.
func (*SortColumn) Descriptor() ([]byte, []int) {
	return file_appbase_proto_rawDescGZIP(), []int{3}
}

var File_appbase_proto protoreflect.FileDescriptor

var file_appbase_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x70, 0x70, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x73, 0x69, 0x65, 0x72, 0x72, 0x61, 0x5f, 0x61, 0x70, 0x70, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9b, 0x01, 0x0a,
	0x06, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x32, 0x35,
	0x36, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x12,
	0x16, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x55, 0x72, 0x69, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x64, 0x64, 0x65, 0x64, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x61, 0x64, 0x64, 0x65, 0x64, 0x22, 0x57, 0x0a, 0x06, 0x53, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x3b, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x22, 0x2a, 0x0a, 0x0d, 0x53, 0x6f, 0x72, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x19, 0x0a, 0x04, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x07, 0x0a, 0x03,
	0x41, 0x73, 0x63, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x65, 0x73, 0x63, 0x10, 0x01, 0x22,
	0x36, 0x0a, 0x0a, 0x53, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x22, 0x28, 0x0a,
	0x04, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x02, 0x42, 0x0f, 0x5a, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_appbase_proto_rawDescOnce sync.Once
	file_appbase_proto_rawDescData = file_appbase_proto_rawDesc
)

func file_appbase_proto_rawDescGZIP() []byte {
	file_appbase_proto_rawDescOnce.Do(func() {
		file_appbase_proto_rawDescData = protoimpl.X.CompressGZIP(file_appbase_proto_rawDescData)
	})
	return file_appbase_proto_rawDescData
}

var file_appbase_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_appbase_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_appbase_proto_goTypes = []interface{}{
	(SortDirection_Enum)(0),       // 0: sierra_app.SortDirection.Enum
	(SortColumn_Enum)(0),          // 1: sierra_app.SortColumn.Enum
	(*Sample)(nil),                // 2: sierra_app.Sample
	(*Source)(nil),                // 3: sierra_app.Source
	(*SortDirection)(nil),         // 4: sierra_app.SortDirection
	(*SortColumn)(nil),            // 5: sierra_app.SortColumn
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_appbase_proto_depIdxs = []int32{
	6, // 0: sierra_app.Source.create_time:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_appbase_proto_init() }
func file_appbase_proto_init() {
	if File_appbase_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_appbase_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sample); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_appbase_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Source); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_appbase_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SortDirection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_appbase_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SortColumn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_appbase_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_appbase_proto_goTypes,
		DependencyIndexes: file_appbase_proto_depIdxs,
		EnumInfos:         file_appbase_proto_enumTypes,
		MessageInfos:      file_appbase_proto_msgTypes,
	}.Build()
	File_appbase_proto = out.File
	file_appbase_proto_rawDesc = nil
	file_appbase_proto_goTypes = nil
	file_appbase_proto_depIdxs = nil
}
