// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Sample is the predicate function for sample builders.
type Sample func(*sql.Selector)

// Source is the predicate function for source builders.
type Source func(*sql.Selector)

// SourceSample is the predicate function for sourcesample builders.
type SourceSample func(*sql.Selector)
