// Code generated by ent, DO NOT EDIT.

package sourcesample

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the sourcesample type in the database.
	Label = "source_sample"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "uri"
	// FieldRelativePath holds the string denoting the relative_path field in the database.
	FieldRelativePath = "relative_path"
	// FieldFilename holds the string denoting the filename field in the database.
	FieldFilename = "filename"
	// EdgeSource holds the string denoting the source edge name in mutations.
	EdgeSource = "source"
	// EdgeSample holds the string denoting the sample edge name in mutations.
	EdgeSample = "sample"
	// EdgeCollection holds the string denoting the collection edge name in mutations.
	EdgeCollection = "collection"
	// EdgeCollectionSamples holds the string denoting the collection_samples edge name in mutations.
	EdgeCollectionSamples = "collection_samples"
	// SampleFieldID holds the string denoting the ID field of the Sample.
	SampleFieldID = "sha256"
	// CollectionFieldID holds the string denoting the ID field of the Collection.
	CollectionFieldID = "id"
	// CollectionSampleFieldID holds the string denoting the ID field of the CollectionSample.
	CollectionSampleFieldID = "id"
	// Table holds the table name of the sourcesample in the database.
	Table = "source_samples"
	// SourceTable is the table that holds the source relation/edge.
	SourceTable = "source_samples"
	// SourceInverseTable is the table name for the Source entity.
	// It exists in this package in order to avoid circular dependency with the "source" package.
	SourceInverseTable = "sources"
	// SourceColumn is the table column denoting the source relation/edge.
	SourceColumn = "source"
	// SampleTable is the table that holds the sample relation/edge.
	SampleTable = "source_samples"
	// SampleInverseTable is the table name for the Sample entity.
	// It exists in this package in order to avoid circular dependency with the "sample" package.
	SampleInverseTable = "samples"
	// SampleColumn is the table column denoting the sample relation/edge.
	SampleColumn = "sample"
	// CollectionTable is the table that holds the collection relation/edge. The primary key declared below.
	CollectionTable = "collection_samples"
	// CollectionInverseTable is the table name for the Collection entity.
	// It exists in this package in order to avoid circular dependency with the "collection" package.
	CollectionInverseTable = "collections"
	// CollectionSamplesTable is the table that holds the collection_samples relation/edge.
	CollectionSamplesTable = "collection_samples"
	// CollectionSamplesInverseTable is the table name for the CollectionSample entity.
	// It exists in this package in order to avoid circular dependency with the "collectionsample" package.
	CollectionSamplesInverseTable = "collection_samples"
	// CollectionSamplesColumn is the table column denoting the collection_samples relation/edge.
	CollectionSamplesColumn = "sample_id"
)

// Columns holds all SQL columns for sourcesample fields.
var Columns = []string{
	FieldID,
	FieldRelativePath,
	FieldFilename,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "source_samples"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"source",
	"sample",
}

var (
	// CollectionPrimaryKey and CollectionColumn2 are the table columns denoting the
	// primary key for the collection relation (M2M).
	CollectionPrimaryKey = []string{"sample_id", "collection_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the SourceSample queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRelativePath orders the results by the relative_path field.
func ByRelativePath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRelativePath, opts...).ToFunc()
}

// ByFilename orders the results by the filename field.
func ByFilename(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFilename, opts...).ToFunc()
}

// BySourceField orders the results by source field.
func BySourceField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSourceStep(), sql.OrderByField(field, opts...))
	}
}

// BySampleField orders the results by sample field.
func BySampleField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSampleStep(), sql.OrderByField(field, opts...))
	}
}

// ByCollectionCount orders the results by collection count.
func ByCollectionCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCollectionStep(), opts...)
	}
}

// ByCollection orders the results by collection terms.
func ByCollection(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCollectionStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCollectionSamplesCount orders the results by collection_samples count.
func ByCollectionSamplesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCollectionSamplesStep(), opts...)
	}
}

// ByCollectionSamples orders the results by collection_samples terms.
func ByCollectionSamples(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCollectionSamplesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSourceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SourceInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, SourceTable, SourceColumn),
	)
}
func newSampleStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SampleInverseTable, SampleFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, SampleTable, SampleColumn),
	)
}
func newCollectionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CollectionInverseTable, CollectionFieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, CollectionTable, CollectionPrimaryKey...),
	)
}
func newCollectionSamplesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CollectionSamplesInverseTable, CollectionSampleFieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, CollectionSamplesTable, CollectionSamplesColumn),
	)
}
