// Code generated by ent, DO NOT EDIT.

package sierraent

import (
	"context"
	"fmt"
	"math"
	"sierra/services/sierra/internal/sierradb/sierraent/predicate"
	"sierra/services/sierra/internal/sierradb/sierraent/sample"
	"sierra/services/sierra/internal/sierradb/sierraent/source"
	"sierra/services/sierra/internal/sierradb/sierraent/sourcesample"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SourceSampleQuery is the builder for querying SourceSample entities.
type SourceSampleQuery struct {
	config
	ctx        *QueryContext
	order      []sourcesample.OrderOption
	inters     []Interceptor
	predicates []predicate.SourceSample
	withSource *SourceQuery
	withSample *SampleQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SourceSampleQuery builder.
func (ssq *SourceSampleQuery) Where(ps ...predicate.SourceSample) *SourceSampleQuery {
	ssq.predicates = append(ssq.predicates, ps...)
	return ssq
}

// Limit the number of records to be returned by this query.
func (ssq *SourceSampleQuery) Limit(limit int) *SourceSampleQuery {
	ssq.ctx.Limit = &limit
	return ssq
}

// Offset to start from.
func (ssq *SourceSampleQuery) Offset(offset int) *SourceSampleQuery {
	ssq.ctx.Offset = &offset
	return ssq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ssq *SourceSampleQuery) Unique(unique bool) *SourceSampleQuery {
	ssq.ctx.Unique = &unique
	return ssq
}

// Order specifies how the records should be ordered.
func (ssq *SourceSampleQuery) Order(o ...sourcesample.OrderOption) *SourceSampleQuery {
	ssq.order = append(ssq.order, o...)
	return ssq
}

// QuerySource chains the current query on the "source" edge.
func (ssq *SourceSampleQuery) QuerySource() *SourceQuery {
	query := (&SourceClient{config: ssq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ssq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ssq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sourcesample.Table, sourcesample.FieldID, selector),
			sqlgraph.To(source.Table, source.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, sourcesample.SourceTable, sourcesample.SourceColumn),
		)
		fromU = sqlgraph.SetNeighbors(ssq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySample chains the current query on the "sample" edge.
func (ssq *SourceSampleQuery) QuerySample() *SampleQuery {
	query := (&SampleClient{config: ssq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ssq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ssq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sourcesample.Table, sourcesample.FieldID, selector),
			sqlgraph.To(sample.Table, sample.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, sourcesample.SampleTable, sourcesample.SampleColumn),
		)
		fromU = sqlgraph.SetNeighbors(ssq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SourceSample entity from the query.
// Returns a *NotFoundError when no SourceSample was found.
func (ssq *SourceSampleQuery) First(ctx context.Context) (*SourceSample, error) {
	nodes, err := ssq.Limit(1).All(setContextOp(ctx, ssq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sourcesample.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ssq *SourceSampleQuery) FirstX(ctx context.Context) *SourceSample {
	node, err := ssq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SourceSample ID from the query.
// Returns a *NotFoundError when no SourceSample ID was found.
func (ssq *SourceSampleQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = ssq.Limit(1).IDs(setContextOp(ctx, ssq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sourcesample.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ssq *SourceSampleQuery) FirstIDX(ctx context.Context) string {
	id, err := ssq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SourceSample entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SourceSample entity is found.
// Returns a *NotFoundError when no SourceSample entities are found.
func (ssq *SourceSampleQuery) Only(ctx context.Context) (*SourceSample, error) {
	nodes, err := ssq.Limit(2).All(setContextOp(ctx, ssq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sourcesample.Label}
	default:
		return nil, &NotSingularError{sourcesample.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ssq *SourceSampleQuery) OnlyX(ctx context.Context) *SourceSample {
	node, err := ssq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SourceSample ID in the query.
// Returns a *NotSingularError when more than one SourceSample ID is found.
// Returns a *NotFoundError when no entities are found.
func (ssq *SourceSampleQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = ssq.Limit(2).IDs(setContextOp(ctx, ssq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sourcesample.Label}
	default:
		err = &NotSingularError{sourcesample.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ssq *SourceSampleQuery) OnlyIDX(ctx context.Context) string {
	id, err := ssq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SourceSamples.
func (ssq *SourceSampleQuery) All(ctx context.Context) ([]*SourceSample, error) {
	ctx = setContextOp(ctx, ssq.ctx, "All")
	if err := ssq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SourceSample, *SourceSampleQuery]()
	return withInterceptors[[]*SourceSample](ctx, ssq, qr, ssq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ssq *SourceSampleQuery) AllX(ctx context.Context) []*SourceSample {
	nodes, err := ssq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SourceSample IDs.
func (ssq *SourceSampleQuery) IDs(ctx context.Context) (ids []string, err error) {
	if ssq.ctx.Unique == nil && ssq.path != nil {
		ssq.Unique(true)
	}
	ctx = setContextOp(ctx, ssq.ctx, "IDs")
	if err = ssq.Select(sourcesample.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ssq *SourceSampleQuery) IDsX(ctx context.Context) []string {
	ids, err := ssq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ssq *SourceSampleQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ssq.ctx, "Count")
	if err := ssq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ssq, querierCount[*SourceSampleQuery](), ssq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ssq *SourceSampleQuery) CountX(ctx context.Context) int {
	count, err := ssq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ssq *SourceSampleQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ssq.ctx, "Exist")
	switch _, err := ssq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("sierraent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ssq *SourceSampleQuery) ExistX(ctx context.Context) bool {
	exist, err := ssq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SourceSampleQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ssq *SourceSampleQuery) Clone() *SourceSampleQuery {
	if ssq == nil {
		return nil
	}
	return &SourceSampleQuery{
		config:     ssq.config,
		ctx:        ssq.ctx.Clone(),
		order:      append([]sourcesample.OrderOption{}, ssq.order...),
		inters:     append([]Interceptor{}, ssq.inters...),
		predicates: append([]predicate.SourceSample{}, ssq.predicates...),
		withSource: ssq.withSource.Clone(),
		withSample: ssq.withSample.Clone(),
		// clone intermediate query.
		sql:  ssq.sql.Clone(),
		path: ssq.path,
	}
}

// WithSource tells the query-builder to eager-load the nodes that are connected to
// the "source" edge. The optional arguments are used to configure the query builder of the edge.
func (ssq *SourceSampleQuery) WithSource(opts ...func(*SourceQuery)) *SourceSampleQuery {
	query := (&SourceClient{config: ssq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ssq.withSource = query
	return ssq
}

// WithSample tells the query-builder to eager-load the nodes that are connected to
// the "sample" edge. The optional arguments are used to configure the query builder of the edge.
func (ssq *SourceSampleQuery) WithSample(opts ...func(*SampleQuery)) *SourceSampleQuery {
	query := (&SampleClient{config: ssq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ssq.withSample = query
	return ssq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RelativePath string `json:"relative_path,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SourceSample.Query().
//		GroupBy(sourcesample.FieldRelativePath).
//		Aggregate(sierraent.Count()).
//		Scan(ctx, &v)
func (ssq *SourceSampleQuery) GroupBy(field string, fields ...string) *SourceSampleGroupBy {
	ssq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SourceSampleGroupBy{build: ssq}
	grbuild.flds = &ssq.ctx.Fields
	grbuild.label = sourcesample.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RelativePath string `json:"relative_path,omitempty"`
//	}
//
//	client.SourceSample.Query().
//		Select(sourcesample.FieldRelativePath).
//		Scan(ctx, &v)
func (ssq *SourceSampleQuery) Select(fields ...string) *SourceSampleSelect {
	ssq.ctx.Fields = append(ssq.ctx.Fields, fields...)
	sbuild := &SourceSampleSelect{SourceSampleQuery: ssq}
	sbuild.label = sourcesample.Label
	sbuild.flds, sbuild.scan = &ssq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SourceSampleSelect configured with the given aggregations.
func (ssq *SourceSampleQuery) Aggregate(fns ...AggregateFunc) *SourceSampleSelect {
	return ssq.Select().Aggregate(fns...)
}

func (ssq *SourceSampleQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ssq.inters {
		if inter == nil {
			return fmt.Errorf("sierraent: uninitialized interceptor (forgotten import sierraent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ssq); err != nil {
				return err
			}
		}
	}
	for _, f := range ssq.ctx.Fields {
		if !sourcesample.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("sierraent: invalid field %q for query", f)}
		}
	}
	if ssq.path != nil {
		prev, err := ssq.path(ctx)
		if err != nil {
			return err
		}
		ssq.sql = prev
	}
	return nil
}

func (ssq *SourceSampleQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SourceSample, error) {
	var (
		nodes       = []*SourceSample{}
		withFKs     = ssq.withFKs
		_spec       = ssq.querySpec()
		loadedTypes = [2]bool{
			ssq.withSource != nil,
			ssq.withSample != nil,
		}
	)
	if ssq.withSource != nil || ssq.withSample != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, sourcesample.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SourceSample).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SourceSample{config: ssq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ssq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ssq.withSource; query != nil {
		if err := ssq.loadSource(ctx, query, nodes, nil,
			func(n *SourceSample, e *Source) { n.Edges.Source = e }); err != nil {
			return nil, err
		}
	}
	if query := ssq.withSample; query != nil {
		if err := ssq.loadSample(ctx, query, nodes, nil,
			func(n *SourceSample, e *Sample) { n.Edges.Sample = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ssq *SourceSampleQuery) loadSource(ctx context.Context, query *SourceQuery, nodes []*SourceSample, init func(*SourceSample), assign func(*SourceSample, *Source)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*SourceSample)
	for i := range nodes {
		if nodes[i].source == nil {
			continue
		}
		fk := *nodes[i].source
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(source.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "source" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (ssq *SourceSampleQuery) loadSample(ctx context.Context, query *SampleQuery, nodes []*SourceSample, init func(*SourceSample), assign func(*SourceSample, *Sample)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*SourceSample)
	for i := range nodes {
		if nodes[i].sample == nil {
			continue
		}
		fk := *nodes[i].sample
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(sample.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "sample" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ssq *SourceSampleQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ssq.querySpec()
	_spec.Node.Columns = ssq.ctx.Fields
	if len(ssq.ctx.Fields) > 0 {
		_spec.Unique = ssq.ctx.Unique != nil && *ssq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ssq.driver, _spec)
}

func (ssq *SourceSampleQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(sourcesample.Table, sourcesample.Columns, sqlgraph.NewFieldSpec(sourcesample.FieldID, field.TypeString))
	_spec.From = ssq.sql
	if unique := ssq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ssq.path != nil {
		_spec.Unique = true
	}
	if fields := ssq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sourcesample.FieldID)
		for i := range fields {
			if fields[i] != sourcesample.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ssq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ssq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ssq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ssq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ssq *SourceSampleQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ssq.driver.Dialect())
	t1 := builder.Table(sourcesample.Table)
	columns := ssq.ctx.Fields
	if len(columns) == 0 {
		columns = sourcesample.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ssq.sql != nil {
		selector = ssq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ssq.ctx.Unique != nil && *ssq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ssq.predicates {
		p(selector)
	}
	for _, p := range ssq.order {
		p(selector)
	}
	if offset := ssq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ssq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SourceSampleGroupBy is the group-by builder for SourceSample entities.
type SourceSampleGroupBy struct {
	selector
	build *SourceSampleQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ssgb *SourceSampleGroupBy) Aggregate(fns ...AggregateFunc) *SourceSampleGroupBy {
	ssgb.fns = append(ssgb.fns, fns...)
	return ssgb
}

// Scan applies the selector query and scans the result into the given value.
func (ssgb *SourceSampleGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ssgb.build.ctx, "GroupBy")
	if err := ssgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SourceSampleQuery, *SourceSampleGroupBy](ctx, ssgb.build, ssgb, ssgb.build.inters, v)
}

func (ssgb *SourceSampleGroupBy) sqlScan(ctx context.Context, root *SourceSampleQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ssgb.fns))
	for _, fn := range ssgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ssgb.flds)+len(ssgb.fns))
		for _, f := range *ssgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ssgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ssgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SourceSampleSelect is the builder for selecting fields of SourceSample entities.
type SourceSampleSelect struct {
	*SourceSampleQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sss *SourceSampleSelect) Aggregate(fns ...AggregateFunc) *SourceSampleSelect {
	sss.fns = append(sss.fns, fns...)
	return sss
}

// Scan applies the selector query and scans the result into the given value.
func (sss *SourceSampleSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sss.ctx, "Select")
	if err := sss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SourceSampleQuery, *SourceSampleSelect](ctx, sss.SourceSampleQuery, sss, sss.inters, v)
}

func (sss *SourceSampleSelect) sqlScan(ctx context.Context, root *SourceSampleQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sss.fns))
	for _, fn := range sss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
