// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// SampleFile is the predicate function for samplefile builders.
type SampleFile func(*sql.Selector)
