// Code generated by ent, DO NOT EDIT.

package hook

import (
	"context"
	"fmt"

	"github.com/luminanceaudio/sierra/src/sierra/services/sierra/internal/sierradb/sierraent"
)

// The CollectionFunc type is an adapter to allow the use of ordinary
// function as Collection mutator.
type CollectionFunc func(context.Context, *sierraent.CollectionMutation) (sierraent.Value, error)

// Mutate calls f(ctx, m).
func (f CollectionFunc) Mutate(ctx context.Context, m sierraent.Mutation) (sierraent.Value, error) {
	if mv, ok := m.(*sierraent.CollectionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *sierraent.CollectionMutation", m)
}

// The CollectionSampleFunc type is an adapter to allow the use of ordinary
// function as CollectionSample mutator.
type CollectionSampleFunc func(context.Context, *sierraent.CollectionSampleMutation) (sierraent.Value, error)

// Mutate calls f(ctx, m).
func (f CollectionSampleFunc) Mutate(ctx context.Context, m sierraent.Mutation) (sierraent.Value, error) {
	if mv, ok := m.(*sierraent.CollectionSampleMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *sierraent.CollectionSampleMutation", m)
}

// The SampleFunc type is an adapter to allow the use of ordinary
// function as Sample mutator.
type SampleFunc func(context.Context, *sierraent.SampleMutation) (sierraent.Value, error)

// Mutate calls f(ctx, m).
func (f SampleFunc) Mutate(ctx context.Context, m sierraent.Mutation) (sierraent.Value, error) {
	if mv, ok := m.(*sierraent.SampleMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *sierraent.SampleMutation", m)
}

// The SourceFunc type is an adapter to allow the use of ordinary
// function as Source mutator.
type SourceFunc func(context.Context, *sierraent.SourceMutation) (sierraent.Value, error)

// Mutate calls f(ctx, m).
func (f SourceFunc) Mutate(ctx context.Context, m sierraent.Mutation) (sierraent.Value, error) {
	if mv, ok := m.(*sierraent.SourceMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *sierraent.SourceMutation", m)
}

// The SourceSampleFunc type is an adapter to allow the use of ordinary
// function as SourceSample mutator.
type SourceSampleFunc func(context.Context, *sierraent.SourceSampleMutation) (sierraent.Value, error)

// Mutate calls f(ctx, m).
func (f SourceSampleFunc) Mutate(ctx context.Context, m sierraent.Mutation) (sierraent.Value, error) {
	if mv, ok := m.(*sierraent.SourceSampleMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *sierraent.SourceSampleMutation", m)
}

// Condition is a hook condition function.
type Condition func(context.Context, sierraent.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m sierraent.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m sierraent.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m sierraent.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op sierraent.Op) Condition {
	return func(_ context.Context, m sierraent.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m sierraent.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m sierraent.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m sierraent.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
func If(hk sierraent.Hook, cond Condition) sierraent.Hook {
	return func(next sierraent.Mutator) sierraent.Mutator {
		return sierraent.MutateFunc(func(ctx context.Context, m sierraent.Mutation) (sierraent.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, sierraent.Delete|sierraent.Create)
func On(hk sierraent.Hook, op sierraent.Op) sierraent.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, sierraent.Update|sierraent.UpdateOne)
func Unless(hk sierraent.Hook, op sierraent.Op) sierraent.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) sierraent.Hook {
	return func(sierraent.Mutator) sierraent.Mutator {
		return sierraent.MutateFunc(func(context.Context, sierraent.Mutation) (sierraent.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []sierraent.Hook {
//		return []sierraent.Hook{
//			Reject(sierraent.Delete|sierraent.Update),
//		}
//	}
func Reject(op sierraent.Op) sierraent.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []sierraent.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...sierraent.Hook) Chain {
	return Chain{append([]sierraent.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() sierraent.Hook {
	return func(mutator sierraent.Mutator) sierraent.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...sierraent.Hook) Chain {
	newHooks := make([]sierraent.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
