// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SampleFilesColumns holds the columns for the "sample_files" table.
	SampleFilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "sha256", Type: field.TypeString},
		{Name: "format", Type: field.TypeString, Nullable: true},
		{Name: "length", Type: field.TypeInt64, Nullable: true},
	}
	// SampleFilesTable holds the schema information for the "sample_files" table.
	SampleFilesTable = &schema.Table{
		Name:       "sample_files",
		Columns:    SampleFilesColumns,
		PrimaryKey: []*schema.Column{SampleFilesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "samplefile_sha256",
				Unique:  true,
				Columns: []*schema.Column{SampleFilesColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SampleFilesTable,
	}
)

func init() {
}
