// Code generated by ent, DO NOT EDIT.

package sierraent

import (
	"context"
	"errors"
	"fmt"
	"sierra/services/sierra/internal/modules/sierradb/sierraent/predicate"
	"sierra/services/sierra/internal/modules/sierradb/sierraent/samplefile"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeSampleFile = "SampleFile"
)

// SampleFileMutation represents an operation that mutates the SampleFile nodes in the graph.
type SampleFileMutation struct {
	config
	op            Op
	typ           string
	id            *int
	sha256        *string
	format        *string
	length        *int64
	addlength     *int64
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*SampleFile, error)
	predicates    []predicate.SampleFile
}

var _ ent.Mutation = (*SampleFileMutation)(nil)

// samplefileOption allows management of the mutation configuration using functional options.
type samplefileOption func(*SampleFileMutation)

// newSampleFileMutation creates new mutation for the SampleFile entity.
func newSampleFileMutation(c config, op Op, opts ...samplefileOption) *SampleFileMutation {
	m := &SampleFileMutation{
		config:        c,
		op:            op,
		typ:           TypeSampleFile,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withSampleFileID sets the ID field of the mutation.
func withSampleFileID(id int) samplefileOption {
	return func(m *SampleFileMutation) {
		var (
			err   error
			once  sync.Once
			value *SampleFile
		)
		m.oldValue = func(ctx context.Context) (*SampleFile, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().SampleFile.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withSampleFile sets the old SampleFile of the mutation.
func withSampleFile(node *SampleFile) samplefileOption {
	return func(m *SampleFileMutation) {
		m.oldValue = func(context.Context) (*SampleFile, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m SampleFileMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m SampleFileMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("sierraent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *SampleFileMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *SampleFileMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().SampleFile.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetSha256 sets the "sha256" field.
func (m *SampleFileMutation) SetSha256(s string) {
	m.sha256 = &s
}

// Sha256 returns the value of the "sha256" field in the mutation.
func (m *SampleFileMutation) Sha256() (r string, exists bool) {
	v := m.sha256
	if v == nil {
		return
	}
	return *v, true
}

// OldSha256 returns the old "sha256" field's value of the SampleFile entity.
// If the SampleFile object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SampleFileMutation) OldSha256(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSha256 is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSha256 requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSha256: %w", err)
	}
	return oldValue.Sha256, nil
}

// ResetSha256 resets all changes to the "sha256" field.
func (m *SampleFileMutation) ResetSha256() {
	m.sha256 = nil
}

// SetFormat sets the "format" field.
func (m *SampleFileMutation) SetFormat(s string) {
	m.format = &s
}

// Format returns the value of the "format" field in the mutation.
func (m *SampleFileMutation) Format() (r string, exists bool) {
	v := m.format
	if v == nil {
		return
	}
	return *v, true
}

// OldFormat returns the old "format" field's value of the SampleFile entity.
// If the SampleFile object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SampleFileMutation) OldFormat(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFormat is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFormat requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFormat: %w", err)
	}
	return oldValue.Format, nil
}

// ClearFormat clears the value of the "format" field.
func (m *SampleFileMutation) ClearFormat() {
	m.format = nil
	m.clearedFields[samplefile.FieldFormat] = struct{}{}
}

// FormatCleared returns if the "format" field was cleared in this mutation.
func (m *SampleFileMutation) FormatCleared() bool {
	_, ok := m.clearedFields[samplefile.FieldFormat]
	return ok
}

// ResetFormat resets all changes to the "format" field.
func (m *SampleFileMutation) ResetFormat() {
	m.format = nil
	delete(m.clearedFields, samplefile.FieldFormat)
}

// SetLength sets the "length" field.
func (m *SampleFileMutation) SetLength(i int64) {
	m.length = &i
	m.addlength = nil
}

// Length returns the value of the "length" field in the mutation.
func (m *SampleFileMutation) Length() (r int64, exists bool) {
	v := m.length
	if v == nil {
		return
	}
	return *v, true
}

// OldLength returns the old "length" field's value of the SampleFile entity.
// If the SampleFile object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SampleFileMutation) OldLength(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLength is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLength requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLength: %w", err)
	}
	return oldValue.Length, nil
}

// AddLength adds i to the "length" field.
func (m *SampleFileMutation) AddLength(i int64) {
	if m.addlength != nil {
		*m.addlength += i
	} else {
		m.addlength = &i
	}
}

// AddedLength returns the value that was added to the "length" field in this mutation.
func (m *SampleFileMutation) AddedLength() (r int64, exists bool) {
	v := m.addlength
	if v == nil {
		return
	}
	return *v, true
}

// ClearLength clears the value of the "length" field.
func (m *SampleFileMutation) ClearLength() {
	m.length = nil
	m.addlength = nil
	m.clearedFields[samplefile.FieldLength] = struct{}{}
}

// LengthCleared returns if the "length" field was cleared in this mutation.
func (m *SampleFileMutation) LengthCleared() bool {
	_, ok := m.clearedFields[samplefile.FieldLength]
	return ok
}

// ResetLength resets all changes to the "length" field.
func (m *SampleFileMutation) ResetLength() {
	m.length = nil
	m.addlength = nil
	delete(m.clearedFields, samplefile.FieldLength)
}

// Where appends a list predicates to the SampleFileMutation builder.
func (m *SampleFileMutation) Where(ps ...predicate.SampleFile) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the SampleFileMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *SampleFileMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.SampleFile, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *SampleFileMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *SampleFileMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (SampleFile).
func (m *SampleFileMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *SampleFileMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.sha256 != nil {
		fields = append(fields, samplefile.FieldSha256)
	}
	if m.format != nil {
		fields = append(fields, samplefile.FieldFormat)
	}
	if m.length != nil {
		fields = append(fields, samplefile.FieldLength)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *SampleFileMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case samplefile.FieldSha256:
		return m.Sha256()
	case samplefile.FieldFormat:
		return m.Format()
	case samplefile.FieldLength:
		return m.Length()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *SampleFileMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case samplefile.FieldSha256:
		return m.OldSha256(ctx)
	case samplefile.FieldFormat:
		return m.OldFormat(ctx)
	case samplefile.FieldLength:
		return m.OldLength(ctx)
	}
	return nil, fmt.Errorf("unknown SampleFile field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SampleFileMutation) SetField(name string, value ent.Value) error {
	switch name {
	case samplefile.FieldSha256:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSha256(v)
		return nil
	case samplefile.FieldFormat:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFormat(v)
		return nil
	case samplefile.FieldLength:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLength(v)
		return nil
	}
	return fmt.Errorf("unknown SampleFile field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *SampleFileMutation) AddedFields() []string {
	var fields []string
	if m.addlength != nil {
		fields = append(fields, samplefile.FieldLength)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *SampleFileMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case samplefile.FieldLength:
		return m.AddedLength()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SampleFileMutation) AddField(name string, value ent.Value) error {
	switch name {
	case samplefile.FieldLength:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddLength(v)
		return nil
	}
	return fmt.Errorf("unknown SampleFile numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *SampleFileMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(samplefile.FieldFormat) {
		fields = append(fields, samplefile.FieldFormat)
	}
	if m.FieldCleared(samplefile.FieldLength) {
		fields = append(fields, samplefile.FieldLength)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *SampleFileMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *SampleFileMutation) ClearField(name string) error {
	switch name {
	case samplefile.FieldFormat:
		m.ClearFormat()
		return nil
	case samplefile.FieldLength:
		m.ClearLength()
		return nil
	}
	return fmt.Errorf("unknown SampleFile nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *SampleFileMutation) ResetField(name string) error {
	switch name {
	case samplefile.FieldSha256:
		m.ResetSha256()
		return nil
	case samplefile.FieldFormat:
		m.ResetFormat()
		return nil
	case samplefile.FieldLength:
		m.ResetLength()
		return nil
	}
	return fmt.Errorf("unknown SampleFile field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *SampleFileMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *SampleFileMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *SampleFileMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *SampleFileMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *SampleFileMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *SampleFileMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *SampleFileMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown SampleFile unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *SampleFileMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown SampleFile edge %s", name)
}
