// Code generated by ent, DO NOT EDIT.

package sierraent

import (
	"context"
	"errors"
	"fmt"
	"sierra/services/sierra/internal/modules/sierradb/sierraent/samplefile"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SampleFileCreate is the builder for creating a SampleFile entity.
type SampleFileCreate struct {
	config
	mutation *SampleFileMutation
	hooks    []Hook
}

// SetSha256 sets the "sha256" field.
func (sfc *SampleFileCreate) SetSha256(s string) *SampleFileCreate {
	sfc.mutation.SetSha256(s)
	return sfc
}

// SetFormat sets the "format" field.
func (sfc *SampleFileCreate) SetFormat(s string) *SampleFileCreate {
	sfc.mutation.SetFormat(s)
	return sfc
}

// SetNillableFormat sets the "format" field if the given value is not nil.
func (sfc *SampleFileCreate) SetNillableFormat(s *string) *SampleFileCreate {
	if s != nil {
		sfc.SetFormat(*s)
	}
	return sfc
}

// SetLength sets the "length" field.
func (sfc *SampleFileCreate) SetLength(i int64) *SampleFileCreate {
	sfc.mutation.SetLength(i)
	return sfc
}

// SetNillableLength sets the "length" field if the given value is not nil.
func (sfc *SampleFileCreate) SetNillableLength(i *int64) *SampleFileCreate {
	if i != nil {
		sfc.SetLength(*i)
	}
	return sfc
}

// Mutation returns the SampleFileMutation object of the builder.
func (sfc *SampleFileCreate) Mutation() *SampleFileMutation {
	return sfc.mutation
}

// Save creates the SampleFile in the database.
func (sfc *SampleFileCreate) Save(ctx context.Context) (*SampleFile, error) {
	return withHooks(ctx, sfc.sqlSave, sfc.mutation, sfc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sfc *SampleFileCreate) SaveX(ctx context.Context) *SampleFile {
	v, err := sfc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sfc *SampleFileCreate) Exec(ctx context.Context) error {
	_, err := sfc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sfc *SampleFileCreate) ExecX(ctx context.Context) {
	if err := sfc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sfc *SampleFileCreate) check() error {
	if _, ok := sfc.mutation.Sha256(); !ok {
		return &ValidationError{Name: "sha256", err: errors.New(`sierraent: missing required field "SampleFile.sha256"`)}
	}
	return nil
}

func (sfc *SampleFileCreate) sqlSave(ctx context.Context) (*SampleFile, error) {
	if err := sfc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sfc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sfc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sfc.mutation.id = &_node.ID
	sfc.mutation.done = true
	return _node, nil
}

func (sfc *SampleFileCreate) createSpec() (*SampleFile, *sqlgraph.CreateSpec) {
	var (
		_node = &SampleFile{config: sfc.config}
		_spec = sqlgraph.NewCreateSpec(samplefile.Table, sqlgraph.NewFieldSpec(samplefile.FieldID, field.TypeInt))
	)
	if value, ok := sfc.mutation.Sha256(); ok {
		_spec.SetField(samplefile.FieldSha256, field.TypeString, value)
		_node.Sha256 = value
	}
	if value, ok := sfc.mutation.Format(); ok {
		_spec.SetField(samplefile.FieldFormat, field.TypeString, value)
		_node.Format = value
	}
	if value, ok := sfc.mutation.Length(); ok {
		_spec.SetField(samplefile.FieldLength, field.TypeInt64, value)
		_node.Length = value
	}
	return _node, _spec
}

// SampleFileCreateBulk is the builder for creating many SampleFile entities in bulk.
type SampleFileCreateBulk struct {
	config
	err      error
	builders []*SampleFileCreate
}

// Save creates the SampleFile entities in the database.
func (sfcb *SampleFileCreateBulk) Save(ctx context.Context) ([]*SampleFile, error) {
	if sfcb.err != nil {
		return nil, sfcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(sfcb.builders))
	nodes := make([]*SampleFile, len(sfcb.builders))
	mutators := make([]Mutator, len(sfcb.builders))
	for i := range sfcb.builders {
		func(i int, root context.Context) {
			builder := sfcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SampleFileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, sfcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, sfcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, sfcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (sfcb *SampleFileCreateBulk) SaveX(ctx context.Context) []*SampleFile {
	v, err := sfcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sfcb *SampleFileCreateBulk) Exec(ctx context.Context) error {
	_, err := sfcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sfcb *SampleFileCreateBulk) ExecX(ctx context.Context) {
	if err := sfcb.Exec(ctx); err != nil {
		panic(err)
	}
}
