name: Build/release

on: push

jobs:
  nogogenerate:
    name: "Go generate check"
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Run go generate
        run: |
          cd src/sierra
          sudo apt install protobuf-compiler
          go generate ./...

      - name: Check for uncommitted changes and untracked files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Go generate changed or created files that are not commited"
            git status --short
            exit 1
          fi

  gosec:
    name: "Gosec Check"
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: src/sierra/...

  release:
    needs: [nogogenerate, gosec]
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.3" # The Go version to download (if necessary) and use.

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          package_root: src/electron
          # If the commit is tagged with a version (e.g. "v1.0.0"), release the app
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
